/**
 * Data Feeds — Real-time & historical data from the data collector
 *
 * These hooks load JSON files generated by scripts/data_collector/
 * and expose them as typed React state.
 *
 * Files are served from public/data/ by Vite's dev server.
 * When data files are missing (e.g. before first run of npm run data:refresh),
 * components gracefully fall back to hardcoded data.
 */

import { useEffect, useState } from 'react';

// ─── Types ─────────────────────────────────────────────────────────────────

export interface ItcLiveQuote {
  ticker: string;
  exchange: string;
  fetchedAt: string;
  source: string;
  companyName: string;
  currentPrice: number | null;
  previousClose: number | null;
  open: number | null;
  dayHigh: number | null;
  dayLow: number | null;
  fiftyTwoWeekHigh: number | null;
  fiftyTwoWeekLow: number | null;
  marketCap: number | null;
  trailingPE: number | null;
  forwardPE: number | null;
  priceToBook: number | null;
  bookValue: number | null;
  epsTrailing: number | null;
  epsForward: number | null;
  dividendRate: number | null;
  dividendYield: number | null;
  revenueTTM: number | null;
  profitTTM: number | null;
  ebitdaTTM: number | null;
  profitMargins: number | null;
  ebitdaMargins: number | null;
  returnOnEquity: number | null;
  debtToEquity: number | null;
  revenueGrowth: number | null;
  earningsGrowth: number | null;
  sector: string | null;
  industry: string | null;
  provenance: { sourceName: string; sourceType: string; fetchedAt: string };
}

export interface PriceRecord {
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  dividends: number;
  stockSplits: number;
}

export interface PriceHistory {
  ticker: string;
  period: string;
  interval: string;
  generatedAt: string;
  source: string;
  count: number;
  records: PriceRecord[];
}

export interface DividendRecord {
  date: string;
  amount: number;
  year: string;
}

export interface DividendHistory {
  ticker: string;
  generatedAt: string;
  source: string;
  count: number;
  records: DividendRecord[];
}

export interface FinancialStatement {
  fiscalYearEnd: string;
  fiscalYear: string;
  [key: string]: number | string | null;
}

export interface FinancialsFeed {
  ticker: string;
  generatedAt: string;
  source: string;
  incomeStatement: FinancialStatement[];
  balanceSheet: FinancialStatement[];
  cashFlow: FinancialStatement[];
}

// ─── Generic data hook ─────────────────────────────────────────────────────

type DataState<T> =
  | { status: 'loading' }
  | { status: 'available'; data: T }
  | { status: 'missing'; error?: string };

function useJsonFeed<T>(url: string): DataState<T> {
  const [state, setState] = useState<DataState<T>>({ status: 'loading' });

  useEffect(() => {
    let cancelled = false;
    setState({ status: 'loading' });

    fetch(url)
      .then(async (res) => {
        if (!res.ok) {
          if (res.status === 404) {
            if (!cancelled) setState({ status: 'missing', error: `Not found: ${url}` });
            return null;
          }
          throw new Error(`HTTP ${res.status}`);
        }
        return res.json() as Promise<T>;
      })
      .then((data) => {
        if (cancelled || data === null) return;
        setState({ status: 'available', data });
      })
      .catch((err: Error) => {
        if (!cancelled) setState({ status: 'missing', error: err.message });
      });

    return () => { cancelled = true; };
  }, [url]);

  return state;
}

// ─── Pre-built hooks ───────────────────────────────────────────────────────

export function useItcLiveQuote() {
  return useJsonFeed<ItcLiveQuote>('/data/itc_live_quote.json');
}

export function useItcPriceHistory() {
  return useJsonFeed<PriceHistory>('/data/itc_price_history.json');
}

export function useItcFinancials() {
  return useJsonFeed<FinancialsFeed>('/data/itc_financials.json');
}

export function useItcDividendHistory() {
  return useJsonFeed<DividendHistory>('/data/itc_dividend_history.json');
}
